language: go

go:
  - 1.17.x

script:
  - go vet .
  - go get -u golang.org/x/lint/golint
  - golint -set_exit_status .
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.43.0
  - golangci-lint run
  - go test -v -race .
