language: go

go:
  - 1.12.x

script:
  - go get honnef.co/go/tools/cmd/staticcheck
  - staticcheck .
  - go vet .
  - go get -u golang.org/x/lint/golint
  - golint -set_exit_status .
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0
  - golangci-lint run
  - go test -v -race .
